### ISSUE TITLE
Agressive user input will spam multiple outputs for "Open or Closed" status. 

### ISSUE THREAD

**Issue by TheWintersFox** [thadkingcole/is_it_open#12]
![image](https://user-images.githubusercontent.com/61752902/85956212-6a4b5480-b952-11ea-9221-55c48d68f15c.png)

**### Expected Behavior**
----
The user would be able to click the button multiple times and the application will print out the open or closed status of the business 1 time.

**### Possible Solution**
---- 
Rewrite code to print out open or closed status of the business in a different area.  Re-evaluate between all group members. 

**### Steps to Reproduce**
----

1.  Pull the most recent version of the application.  This can be done by going to https://github.com/thadkingcole/is_it_open/pull/11/files
2. Click the clipboard next to covid-api-testing text
![image](https://user-images.githubusercontent.com/61752902/85956381-8ac7de80-b953-11ea-9387-74f641781d17.png)
3.  Open terminal and make sure you're in the master branch of is_it_open
4. Switch into the covid-api-testing branch by doing the command "git checkout covid-api-testing", then do a "git pull" to make sure your app is up to date. Now do the command "code ." to open the code.
5. Click on the index file then right click the index file to "open in default browser"
6. Type in any city, county, or state and then spam the Search Button.

**### Result**
----
When making agressive user input with multiple button presses the results will print out multiple open or closed statuses under each yelp business return.

**Comment by thadkingcole** [comment]
related: #13
