### ISSUE TITLE
Range?

### ISSUE THREAD

**Issue by diuguide** [thadkingcole/is_it_open#21]
Since we've already linked the closest county in the code, could we not easily add a range bar or drop down?

- [ ] build range bar for miles radius of search area.

**Comment by thadkingcole** [comment]
I will have to research this one. I am not sure how the yelp API decides what results to show. It could be that it returns the closest 5 results, in which case adjusting the radius of the search will not affect what businesses are shown. If it returns the highest rated results in the search radius, then giving the user an optional search radius parameter would definitely be useful.
