### ISSUE TITLE
2 "show 5 more" buttons sometimes appear at bottom of results

### ISSUE THREAD

**Issue by thadkingcole** [thadkingcole/is_it_open#37]
steps to reproduce:

1. submit a search in location A.
1. click the "show 5 more" button at bottom of page.
1. submit a search in location B.
1. there should be 2 different "show 5 more" buttons at the bottom of the page.

**Comment by diuguide** [comment]
is this due to over clicking?

**Comment by thadkingcole** [comment]
I don't think so... I have the button being made within the yelp API call, and I attach the event listener with its call-back function to the button still within the API call. Because I only remove the button once the user has been shown 50 results (or fewer if the API returns fewer), if the user does another search after clicking it once, that button sticks around.
